add cbr support
terraform-ibm-modules/terraform-ibm-scc-workload-protection pull request #142
Opened 2024-08-29 07:58 UTC by Aayush-Abhyarthi

### Description

This PR adds cbr support in scc workload protection module

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-08-29 08:19 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-09-02 06:37 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-09-05 09:58 UTC, akocbek requested changes

2024-09-05 09:58 UTC, akocbek commented on main.tf
> +  resources = [{
shall we add support for tags as well?
similar as we have for cos buckets https://github.com/terraform-ibm-modules/terraform-ibm-cos/blob/b9cc0f04153b289e582f80175d9bc93d648189e3/main.tf#L376

2024-09-05 19:07 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-09-11 16:08 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-09-16 16:07 UTC, ocofaigh commented
/run pipeline

2024-09-16 16:07 UTC, ocofaigh commented
@Aayush-Abhyarthi @akocbek PR has been open for 3 weeks - are we all good here?

2024-09-16 16:19 UTC, Aayush-Abhyarthi commented
> @Aayush-Abhyarthi @akocbek PR has been open for 3 weeks - are we all good here?

Its ok from my side. Was waiting for the re-review of the proposed changes

2024-09-16 17:19 UTC, ocofaigh commented
Please reach out to @akocbek for a re-review so as it looks like he originally reviewed it. Thanks

2024-09-17 09:21 UTC, akocbek approved these changes

2024-09-17 09:47 UTC, merged

2024-09-17 09:47 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.4.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-scc-workload-protection/releases/tag/v1.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: